steps:
  - id: Docker Build
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/mail:$SHORT_SHA", "."]
      
  - id: Docker Tag
    name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/mail:$SHORT_SHA', 'gcr.io/$PROJECT_ID/mail:latest']

  - id: Docker Push version
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/mail:$SHORT_SHA"]
      
  - id: Docker Push latest
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/mail:latest"]
