steps:
- id: Docker Build
    name: "book-fe"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/budget:$SHORT_SHA", "."]
      
  - id: Docker Tag
    name: 'book-fe'
    args: ['tag', 'gcr.io/$PROJECT_ID/budget:$SHORT_SHA', 'gcr.io/$PROJECT_ID/budget:latest']
